-- Adoption of the system that already exists.
--
-- Three shifts from 0001, all of them because the live setup is looser than
-- the schema first assumed:
--
-- 1. A domain does not need an organization. Org structure is still being
--    worked out, so "unassigned" is a normal, durable state -- not an error
--    to be filled in before a domain can be recorded.
-- 2. A vhost is a *file*, not a domain. The hand-written ones routinely serve
--    several names (apex, www, an old brand) across more than one domain, so
--    the file is the row and the names hang off it.
-- 3. Findings persist between scans, so "this has been broken for months" is
--    visible instead of being rediscovered every run.

ALTER TABLE domains MODIFY COLUMN org_id VARCHAR(64) NULL DEFAULT NULL;

-- 0001 modelled one vhost per domain, generated by us. Adoption breaks both
-- halves of that assumption.
--
-- The index swap at the end (drop the unique `vhosts_domain`, add a
-- plain one back under the same name) has to happen in the same
-- statement as everything else here, not a separate `ALTER TABLE` per
-- clause: `vhosts_domain` is what `vhosts_domain_fk` (0001) relies on to
-- support its foreign key, and InnoDB refuses to drop the last index
-- backing a live FK constraint. Folded into one statement, InnoDB sees
-- the replacement index appear in the same DDL operation and allows it;
-- as two statements, the first (the bare `DROP INDEX`) leaves `domain_id`
-- with no supporting index at all for the moment in between, which it
-- refuses outright (MySQL error 1553).
ALTER TABLE vhosts
  MODIFY COLUMN domain_id BIGINT UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN runner_id VARCHAR(64) NULL DEFAULT NULL,
  MODIFY COLUMN template  VARCHAR(128) NULL DEFAULT NULL,
  -- 'adopted': a file someone wrote by hand. We record it, show it, and never
  -- rewrite it. 'generated': ours, rendered from `template`, safe to rewrite.
  ADD COLUMN origin ENUM('adopted','generated') NOT NULL DEFAULT 'generated',
  -- Path relative to the tree root, and the hash of what we last saw there,
  -- so a hand edit to a generated file shows up as drift instead of being
  -- silently overwritten on the next render.
  ADD COLUMN source_path  VARCHAR(512) NULL DEFAULT NULL,
  ADD COLUMN file_sha256  CHAR(64)     NULL DEFAULT NULL,
  ADD COLUMN adopted_at   TIMESTAMP    NULL DEFAULT NULL,
  -- One vhost per file on disk. The old unique key (one per domain) cannot
  -- hold once a file serves several domains.
  DROP INDEX vhosts_domain,
  ADD KEY vhosts_domain (domain_id),
  ADD UNIQUE KEY vhosts_source_path (source_path);

CREATE TABLE IF NOT EXISTS vhost_server_names (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  vhost_id    BIGINT UNSIGNED NOT NULL,
  -- As written in the config, `_` and `*.example.com` included.
  name        VARCHAR(253)    NOT NULL,
  -- Filled in when the name maps to a domain we know about; NULL when it
  -- does not, which is itself worth seeing.
  domain_id   BIGINT UNSIGNED NULL DEFAULT NULL,
  is_wildcard TINYINT(1)      NOT NULL DEFAULT 0,
  UNIQUE KEY vhost_server_names_unique (vhost_id, name),
  -- Not unique: the same name appearing twice across files is exactly the
  -- `duplicate_server_name` finding, and the schema must be able to hold the
  -- broken state in order to report it.
  KEY vhost_server_names_name (name),
  KEY vhost_server_names_domain (domain_id),
  CONSTRAINT vhost_server_names_vhost_fk FOREIGN KEY (vhost_id) REFERENCES vhosts (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inventory_scans (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tree_root     VARCHAR(512)    NOT NULL,
  started_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at   TIMESTAMP       NULL DEFAULT NULL,
  file_count    INT             NOT NULL DEFAULT 0,
  server_count  INT             NOT NULL DEFAULT 0,
  cert_count    INT             NOT NULL DEFAULT 0,
  finding_count INT             NOT NULL DEFAULT 0,
  ok            TINYINT(1)      NOT NULL DEFAULT 1,
  last_error    TEXT            NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inventory_findings (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code        VARCHAR(48)     NOT NULL,
  severity    ENUM('info','warn','error') NOT NULL DEFAULT 'warn',
  -- What the finding is about: a domain, a file path, a cert directory.
  subject     VARCHAR(512)    NOT NULL,
  domain_id   BIGINT UNSIGNED NULL DEFAULT NULL,
  detail      JSON            NULL,
  first_seen  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Set when a scan no longer reproduces it. Kept rather than deleted, so a
  -- problem that keeps coming back is visible as such.
  resolved_at TIMESTAMP       NULL DEFAULT NULL,
  -- One row per (code, subject): a re-scan touches `last_seen` instead of
  -- growing the table by one row per run.
  UNIQUE KEY inventory_findings_unique (code, subject(191)),
  KEY inventory_findings_code (code),
  KEY inventory_findings_open (resolved_at),
  KEY inventory_findings_domain (domain_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
